#' Evanno plot function
#' 
#' Plots Evanno delta K plot from structure output data, ggplot-based so can be styled with additional ggplot arguments, eg. plot_Evanno + theme(axis.text = element_text(size = 10))
#' @import ggplot2
#' @import ggtext
#' @import pophelper
#' @import tidyr
#' @param structure_output_path path for the directory with structure output files
#' @param full should also other plots be generated: mean likelihood L(K), its rate of change L'(K)=L(K)), and absolute values of the second order rate of change |L''(K)|=|L'(K+1)-L'(K)| ?
#' @details Plots are based on Evanno (Evanno, G., Regnaut, S., Goudet, J. (2005). Detecting the number of clusters of individuals using the software STRUCTURE: a simulation study. Molecular ecology, 14(8), 2611-2620) method, data is generated by the pophelper package (Francis, R. M. (2017). POPHELPER: an R package and web app to analyse and visualize population structure. Molecular Ecology Resources, 17(1), 27-32. DOI: 10.1111/1755-0998.12509).
#' @export
#' @examples
#' structure_output_path <- "test_data/structure/Aal_admix_out"
#' plot_Evanno(structure_output_path)

plot_Evanno <- function(structure_output_path, full = FALSE) {
  # Structure
  sfiles <- list.files(structure_output_path, full.names = T)
  slist <- readQ(sfiles, filetype="structure", indlabfromfile = T)
  # runs summary:
  stats_str <- summariseQ(tabulateQ(slist))
  evanno <- evannoMethodStructure(data=stats_str, exportplot=F,returnplot=F,returndata=T)
  # plot
  if(full == FALSE){
    evanno_plot <- ggplot(data=evanno[2:(nrow(evanno)-1),], aes(x = k, y = deltaK)) +
                   geom_line() +
                   geom_point() +
                   scale_x_continuous(breaks=evanno$k) +
                   ylab("\u0394*K*") +
                   xlab("K") +
                   theme(axis.title.y = element_markdown(),
                         axis.title.x = element_text(face = "italic"))
  } else{
    evanno_mean <- pivot_longer(evanno[,-c(1,2,4,6,7,8,10,11,13,14)], -c(k), values_to = "Value", names_to = "Parameter")
    evanno_mean$Parameter <- gsub("mean", "", evanno_mean$Parameter)

    evanno_min <- pivot_longer(evanno[,c(3,7,11,14)], -c(k), values_to = "Min", names_to = "Parameter")
    evanno_min$Parameter <- gsub("min", "", evanno_min$Parameter)
      
    evanno_max <- pivot_longer(evanno[,c(3,8,10,13)], -c(k), values_to = "Max", names_to = "Parameter")
    evanno_max$Parameter <- gsub("max", "", evanno_max$Parameter)
    
    evanno <- merge(merge(evanno_mean, evanno_min, by = c("k", "Parameter"), all.x = TRUE), evanno_max, by = c("k", "Parameter"), all.x = TRUE)
    evanno$Parameter <- factor(evanno$Parameter, levels = c("elpd", "lnk1", "lnk2", "deltaK"))
    
    evanno <- evanno[evanno$Parameter == "deltaK" | evanno$Parameter == "elpd", ]

    facet_labels <- c(
                    `elpd` = "*L*(*K*) \u00B1 SD",
                    #`lnk1` = "*L*\u2032(*K*) \u00B1 SD",
                    #`lnk2` = "|*L*\u2033(*K*)| \u00B1 SD",
                    `deltaK` = "\u0394*K* "
                    )
    
    evanno_plot <- ggplot(data=evanno, aes(x=k, y=Value, ymin=Min, ymax=Max)) +
                   geom_line() +
                   geom_point() +
                   geom_errorbar(width=.3, linewidth=.3) +
                   scale_x_continuous(breaks=evanno$k) +
                   facet_wrap(~Parameter , scales = "free", labeller = as_labeller(facet_labels)) +
                   xlab("K") +
                   theme(strip.text = ggtext::element_markdown(),
                         axis.title.x = element_text(face = "italic"))
  }
  return(evanno_plot)
}
